### ISSUE TITLE
bug de compilation sur le meta_social "twitter_card_type"

### ISSUE THREAD

**Issue by SylvainLapoix** [datactivist/slides_datactivist#3]
https://github.com/datactivist/slides_datactivist/blob/fa5e3121e5016a6a5390b409b1f8eea022d02d8b/inst/rmarkdown/templates/xaringan/skeleton/skeleton.Rmd#L44

Je reçois l'erreur suivante : 
```
processing file: Untitled.Rmd
Quitting from lines 30-47 (Untitled.Rmd) 
Error in parse(text = x, srcfile = src) : <text>:15:5: unexpected symbol
14:     og_site_name = "Datactivist"
15:     twitter_card_type
        ^
Calls: <Anonymous> ... <Anonymous> -> parse_all -> parse_all.character -> parse
Exécution arrêtée
```

Je n'ai pas trouvé la source de ce problème dans `metathis`.

**Comment by joelgombin** [comment]
fixed by https://github.com/datactivist/slides_datactivist/commit/01527460a59e71c0f78338016f52b5f17f46e8bf
